openapi: 3.0.1
info:
  description: "\nBefore using this API, we recommend you read our **[Authorization\
    \ Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)**\
    \ for more information on how to generate an access token. \n  \nPlease also be\
    \ aware that our test environment is based on a subset of the production, this\
    \ API in test only returns a few selected cities. You can find the list in our\
    \ **[data collection](https://github.com/amadeus4dev/data-collection)**."
  title: Tours and Activities
  version: 1.0.2
  x-logo:
    url: https://amadeus.com/images/en/technology/mobile-tablet/mobile-woman-office-city.jpg.transform/medium/img.jpg
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/amadeus4dev/amadeus-open-api-specification/main/spec/json/ToursandActivities_v1_swagger_specification.json
    version: "2.0"
  x-providerName: amadeus.com
  x-release-note:
    "1.0":
    - First version
  x-serviceName: amadeus-tours-and-activities
  x-status: validated
  x-tags:
  - '#ama-for-dev'
servers:
- url: https://test.api.amadeus.com/v1
paths:
  /shopping/activities:
    get:
      operationId: list_activities
      parameters:
      - description: Latitude (decimal coordinates)
        example: 41.397158
        in: query
        name: latitude
        required: true
        schema:
          type: number
      - description: Longitude (decimal coordinates)
        example: 2.160873
        in: query
        name: longitude
        required: true
        schema:
          type: number
      - description: "radius of the search in Kilometer. Can be from 0 to 20, default\
          \ value is 1 Km."
        in: query
        name: radius
        schema:
          default: 1
          type: integer
      responses:
        "200":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Successful_Search'
          description: Successful Operation
        "400":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_400'
          description: "Code   | Title\n-------|----------------\n477    | INVALID\
            \ FORMAT\n572    | INVALID OPTION\n4926   | INVALID DATA RECEIVED\n32171\
            \  | MANDATORY DATA MISSING\t     \n"
        default:
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_500'
          description: Unexpected Error
      summary: Returns Activities around a given location
      tags:
      - Search
      x-openapi-router-controller: openapi_server.controllers.search_controller
  /shopping/activities/by-square:
    get:
      operationId: list_activities_by_square
      parameters:
      - description: Latitude north of bounding box (decimal coordinates)
        example: 41.397158
        in: query
        name: north
        required: true
        schema:
          type: number
      - description: Longitude west of bounding box (decimal coordinates)
        example: 2.160873
        in: query
        name: west
        required: true
        schema:
          type: number
      - description: Latitude south of bounding box (decimal coordinates)
        example: 41.394582
        in: query
        name: south
        required: true
        schema:
          type: number
      - description: Longitude east of bounding box (decimal coordinates)
        example: 2.177181
        in: query
        name: east
        required: true
        schema:
          type: number
      responses:
        "200":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Successful_Search'
          description: Successful Operation
        "400":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_400'
          description: "Code   | Title\n-------|----------------\n477    | INVALID\
            \ FORMAT\n572    | INVALID OPTION\n4926   | INVALID DATA RECEIVED\n32171\
            \  | MANDATORY DATA MISSING\t     \n"
        default:
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_500'
          description: Unexpected Error
      summary: Returns Activities around a given location
      tags:
      - Search
      x-openapi-router-controller: openapi_server.controllers.search_controller
  /shopping/activities/{activityId}:
    get:
      operationId: g_et_activity
      parameters:
      - in: path
        name: activityId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Successful_Search_1'
          description: Successful Operation
        "400":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_400'
          description: "Code   | Title\n-------|----------------\n572    | INVALID\
            \ OPTION\t     \n"
        "404":
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_404'
          description: Not Found
        default:
          content:
            application/vnd.amadeus+json:
              schema:
                $ref: '#/components/schemas/Error_500'
          description: Unexpected Error
      summary: Retrieve one activity by its id
      tags:
      - Retrieve
      x-openapi-router-controller: openapi_server.controllers.retrieve_controller
components:
  parameters:
    activityId:
      example: "23642"
      in: path
      name: activityId
      required: true
      schema:
        type: string
  responses:
    "404":
      content:
        application/vnd.amadeus+json:
          schema:
            $ref: '#/components/schemas/Error_404'
      description: Not Found
    "500":
      content:
        application/vnd.amadeus+json:
          schema:
            $ref: '#/components/schemas/Error_500'
      description: Unexpected Error
    "400_Retreive":
      content:
        application/vnd.amadeus+json:
          schema:
            $ref: '#/components/schemas/Error_400'
      description: "Code   | Title\n-------|----------------\n572    | INVALID OPTION\t\
        \     \n"
    "400_Search":
      content:
        application/vnd.amadeus+json:
          schema:
            $ref: '#/components/schemas/Error_400'
      description: "Code   | Title\n-------|----------------\n477    | INVALID FORMAT\n\
        572    | INVALID OPTION\n4926   | INVALID DATA RECEIVED\n32171  | MANDATORY\
        \ DATA MISSING\t     \n"
    activities:
      content:
        application/vnd.amadeus+json:
          schema:
            example:
              data:
              - bookingLink: https://b2c.mla.cloud/c/QCejqyor?c=2WxbgL36
                geoCode:
                  latitude: "40.414000"
                  longitude: "-3.691000"
                id: "23642"
                name: Skip-the-line tickets to the Prado Museum
                pictures:
                - https://images.musement.com/cover/0001/07/prado-museum-tickets_header-6456.jpeg?w=500
                price:
                  amount: "16.00"
                  currencyCode: EUR
                rating: "4.500000"
                self:
                  href: https://test.api.amadeus.com/v1/shopping/activities/23642
                  methods:
                  - GET
                shortDescription: "Book your tickets for the Prado Museum in Madrid,\
                  \ discover masterpieces by Vel치zquez, Goya, Mantegna, Raphael, Tintoretto\
                  \ and access all temporary exhibitions."
                type: activity
              meta:
                count: "1"
                links:
                  self: https://test.api.amadeus.com/v1/shopping/activities?longitude=-3.69170868&latitude=40.41436995&radius=1
            properties:
              data:
                items:
                  $ref: '#/components/schemas/Activity'
                type: array
              meta:
                $ref: '#/components/schemas/Collection_Meta'
              warnings:
                items:
                  $ref: '#/components/schemas/Issue'
                type: array
            required:
            - data
            title: Successful Search
            type: object
      description: Successful Operation
    activity:
      content:
        application/vnd.amadeus+json:
          schema:
            example:
              data:
                bookingLink: https://b2c.mla.cloud/c/QCejqyor?c=2WxbgL36
                geoCode:
                  latitude: "40.414000"
                  longitude: "-3.691000"
                id: "23642"
                name: Skip-the-line tickets to the Prado Museum
                pictures:
                - https://images.musement.com/cover/0001/07/prado-museum-tickets_header-6456.jpeg?w=500
                price:
                  amount: "16.00"
                  currencyCode: EUR
                rating: "4.500000"
                self:
                  href: https://test.api.amadeus.com/v1/shopping/activities/23642
                  methods:
                  - GET
                shortDescription: "Book your tickets for the Prado Museum in Madrid,\
                  \ discover masterpieces by Vel치zquez, Goya, Mantegna, Raphael, Tintoretto\
                  \ and access all temporary exhibitions."
                type: activity
              meta:
                self: https://test.api.amadeus.com/v1/shopping/activities/23642
            properties:
              data:
                $ref: '#/components/schemas/Activity'
              meta:
                $ref: '#/components/schemas/Collection_Meta'
              warnings:
                items:
                  $ref: '#/components/schemas/Issue'
                type: array
            required:
            - data
            title: Successful Search
            type: object
      description: Successful Operation
  schemas:
    Activity:
      description: Activity description
      properties:
        bookingLink:
          description: url to book the activity
          title: bookingLink
          type: string
        description:
          description: full description of the activity
          title: description
          type: string
        geoCode:
          $ref: '#/components/schemas/GeoCode'
        id:
          description: unique id of the ressource
          readOnly: true
          title: id
          type: string
        minimumDuration:
          description: Minimum recommended duration for the activity
          title: minimumDuration
          type: string
        name:
          description: activity name
          title: name
          type: string
        pictures:
          description: link to picture related to the activity
          items:
            type: string
          title: pictures
          type: array
        price:
          $ref: '#/components/schemas/ElementaryPrice'
        rating:
          description: rating of the activity
          title: rating
          type: string
        self:
          $ref: '#/components/schemas/Link'
        shortDescription:
          description: short description of the activity
          title: shortDescription
          type: string
        type:
          description: the ressource name
          readOnly: true
          title: type
          type: string
      title: Activity
      type: object
    Collection_Meta:
      properties:
        count:
          example: 1
          title: count
          type: integer
        links:
          $ref: '#/components/schemas/CollectionLinks'
      title: Collection_Meta
      type: object
    ElementaryPrice:
      description: elementaryPrice
      properties:
        amount:
          description: "Amount of the fare. could be alpha numeric. Ex- 500.20 or\
            \ 514.13A, 'A'signifies additional collection."
          title: amount
          type: string
        currencyCode:
          description: Currency type of the fare.
          title: currencyCode
          type: string
      title: ElementaryPrice
      type: object
    Error_400:
      example:
        errors:
        - code: 477
          detail: invalid query parameter format
          source:
            example: CDG
            parameter: airport
          status: 400
          title: INVALID FORMAT
      properties:
        errors:
          items:
            $ref: '#/components/schemas/Issue'
          type: array
      required:
      - errors
      title: Error_400
      type: object
    Error_404:
      example:
        errors:
        - code: 1797
          detail: no response found for this query parameter
          source:
            parameter: airport
          status: 404
          title: NOT FOUND
      properties:
        errors:
          items:
            $ref: '#/components/schemas/Issue'
          type: array
      required:
      - errors
      title: Error_404
      type: object
    Error_500:
      example:
        errors:
        - code: 141
          status: 500
          title: SYSTEM ERROR HAS OCCURRED
      properties:
        errors:
          items:
            $ref: '#/components/schemas/Issue'
          type: array
      required:
      - errors
      title: Error_500
      type: object
    GeoCode:
      description: geo position
      properties:
        latitude:
          description: latitude of the location
          example: 43.580418
          format: double
          title: latitude
          type: number
        longitude:
          description: longitude of the location
          example: 7.125102
          format: double
          title: longitude
          type: number
      title: GeoCode
      type: object
    Issue:
      properties:
        code:
          description: an application-specific error code
          format: int64
          title: code
          type: integer
        detail:
          description: explanation of the error
          title: detail
          type: string
        source:
          $ref: '#/components/schemas/Issue_Source'
        status:
          description: the HTTP status code applicable to this error
          title: status
          type: integer
        title:
          description: a short summary of the error
          title: title
          type: string
      title: Issue
      type: object
    Link:
      example:
        href: string
      properties:
        href:
          format: uri
          type: string
        methods:
          items:
            enum:
            - GET
            - PUT
            - DELETE
            - POST
            - PATCH
            type: string
          type: array
      title: Link
      type: object
    Successful_Search:
      example:
        data:
        - bookingLink: https://b2c.mla.cloud/c/QCejqyor?c=2WxbgL36
          geoCode:
            latitude: "40.414000"
            longitude: "-3.691000"
          id: "23642"
          name: Skip-the-line tickets to the Prado Museum
          pictures:
          - https://images.musement.com/cover/0001/07/prado-museum-tickets_header-6456.jpeg?w=500
          price:
            amount: "16.00"
            currencyCode: EUR
          rating: "4.500000"
          self:
            href: https://test.api.amadeus.com/v1/shopping/activities/23642
            methods:
            - GET
          shortDescription: "Book your tickets for the Prado Museum in Madrid, discover\
            \ masterpieces by Vel치zquez, Goya, Mantegna, Raphael, Tintoretto and access\
            \ all temporary exhibitions."
          type: activity
        meta:
          count: "1"
          links:
            self: https://test.api.amadeus.com/v1/shopping/activities?longitude=-3.69170868&latitude=40.41436995&radius=1
      properties:
        data:
          items:
            $ref: '#/components/schemas/Activity'
          type: array
        meta:
          $ref: '#/components/schemas/Collection_Meta'
        warnings:
          items:
            $ref: '#/components/schemas/Issue'
          type: array
      required:
      - data
      title: Successful Search
      type: object
    Successful_Search_1:
      example:
        data:
          bookingLink: https://b2c.mla.cloud/c/QCejqyor?c=2WxbgL36
          geoCode:
            latitude: "40.414000"
            longitude: "-3.691000"
          id: "23642"
          name: Skip-the-line tickets to the Prado Museum
          pictures:
          - https://images.musement.com/cover/0001/07/prado-museum-tickets_header-6456.jpeg?w=500
          price:
            amount: "16.00"
            currencyCode: EUR
          rating: "4.500000"
          self:
            href: https://test.api.amadeus.com/v1/shopping/activities/23642
            methods:
            - GET
          shortDescription: "Book your tickets for the Prado Museum in Madrid, discover\
            \ masterpieces by Vel치zquez, Goya, Mantegna, Raphael, Tintoretto and access\
            \ all temporary exhibitions."
          type: activity
        meta:
          self: https://test.api.amadeus.com/v1/shopping/activities/23642
      properties:
        data:
          $ref: '#/components/schemas/Activity'
        meta:
          $ref: '#/components/schemas/Collection_Meta'
        warnings:
          items:
            $ref: '#/components/schemas/Issue'
          type: array
      required:
      - data
      title: Successful Search
      type: object
    CollectionLinks:
      example:
        self: https://test.api.amadeus.com/v1/area/resources?param=value
      properties:
        first:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
        last:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
        next:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
        previous:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
        self:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
        up:
          example: https://test.api.amadeus.com/v1/area/resources?...
          format: uri
          type: string
      title: CollectionLinks
      type: object
    Issue_Source:
      description: an object containing references to the source of the error
      properties:
        example:
          description: a string indicating an example of the right value
          title: example
          type: string
        parameter:
          description: a string indicating which URI query parameter caused the issue
          title: parameter
          type: string
        pointer:
          description: "a JSON Pointer [RFC6901] to the associated entity in the request\
            \ document"
          title: pointer
          type: string
      title: Issue_Source
      type: object
x-generatedAt: 2020-09-02T09:57:40.390Z
x-original-swagger-version: "2.0"
