openapi: 3.0.1
info:
  description: Execute SQL queries against a Datasette database and return the results
    as JSON
  title: Datasette API
  version: v1
  x-apisguru-categories:
  - developer_tools
  x-origin:
  - format: openapi
    url: https://datasette.io/-/chatgpt-openapi-schema.yml
    version: "3.0"
  x-providerName: datasette.local
servers:
- url: http://datasette.local
- url: https://datasette.io
paths:
  /content.json:
    get:
      description: "Accepts SQLite SQL query, returns JSON. Does not allow PRAGMA\
        \ statements."
      operationId: query
      parameters:
      - description: The SQL query to be executed
        explode: true
        in: query
        name: sql
        required: true
        schema:
          type: string
        style: form
      - description: The shape of the response data. Must be "array"
        explode: true
        in: query
        name: _shape
        required: true
        schema:
          enum:
          - array
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: object
                type: array
          description: Successful SQL results
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Execute a SQLite SQL query against the content database
      x-accepts:
      - application/json
components:
  schemas: {}

