openapi: 3.0.1
info:
  description: Subscription client provides an interface to create and manage Azure
    subscriptions programmatically.
  title: SubscriptionClient
  version: 2018-11-01-preview
  x-apisguru-categories:
  - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
  - format: swagger
    url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/subscription/resource-manager/Microsoft.Subscription/preview/2018-11-01-preview/subscriptions.json
    version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: subscription-subscriptions
  x-tags:
  - Azure
  - Microsoft
servers:
- url: https://management.azure.com/
security:
- azure_auth:
  - user_impersonation
paths:
  ? /providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/invoiceSections/{invoiceSectionName}/providers/Microsoft.Subscription/createSubscription
  : post:
      description: The operation to create a new WebDirect or EA Azure subscription.
      operationId: SubscriptionFactory_CreateSubscription
      parameters:
      - description: The name of the Microsoft Customer Agreement billing account
          for which you want to create the subscription.
        in: path
        name: billingAccountName
        required: true
        schema:
          type: string
      - description: The name of the billing profile in the billing account for which
          you want to create the subscription.
        in: path
        name: billingProfileName
        required: true
        schema:
          type: string
      - description: The name of the invoice section in the billing account for which
          you want to create the subscription.
        in: path
        name: invoiceSectionName
        required: true
        schema:
          type: string
      - description: Version of the API to be used with the client request. Current
          version is 2018-11-01-preview
        in: query
        name: api-version
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModernSubscriptionCreationParameters'
        description: The subscription creation parameters.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionCreationResult'
          description: Normal response for a successful query. The response body will
            contain the data that matches the filters specified in the query parameters.
        "202":
          content: {}
          description: Accepted. Subscription creation is in progress.
          headers:
            Retry-After:
              description: The amount of delay to use while the status of the operation
                is checked. The value is expressed in seconds.
              schema:
                type: integer
            Location:
              description: GET this URL to retrieve the status of the asynchronous
                operation.
              schema:
                type: string
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      x-ms-examples:
        createSubscription:
          parameters:
            api-version: 2018-11-01-preview
            billingAccountName: 0aa27f2b-ec7f-5a65-71f6-a5ff0897bd55:ae0dae1e-de9a-41f6-8257-76b055d98372_2019-05-31
            billingProfileName: 27VR-HDWX-BG7-TGB
            body:
              billingProfileId: /providers/Microsoft.Billing/billingAccounts/0aa27f2b-ec7f-5a65-71f6-a5ff0897bd55:ae0dae1e-de9a-41f6-8257-76b055d98372_2019-05-31/billingProfiles/27VR-HDWX-BG7-TGB
              costCenter: "135366376"
              displayName: Contoso MCA subscription
              owner:
                objectId: 973034ff-acb7-409c-b731-e789672c7b32
              skuId: "0001"
            invoiceSectionName: JGF7-NSBG-PJA-TGB
          responses:
            "200":
              body:
                subscriptionLink: /subscriptions/d0d6ee57-6530-4fca-93a6-b755a070be35
            "202":
              headers:
                Location: https://management.azure.com/providers/Microsoft.Subscription/subscriptionOperations/ODdmYTU0MDktODc5YS00ZTEzLTg2MWItNTQ4ZjYxNzBlOTQw?api-version=2018-03-01-preview
                Retry-After: 8
      x-ms-long-running-operation: true
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts:
      - application/json
  ? /providers/Microsoft.Billing/billingAccounts/{billingAccountName}/customers/{customerName}/providers/Microsoft.Subscription/createSubscription
  : post:
      description: The operation to create a new CSP subscription.
      operationId: SubscriptionFactory_CreateCspSubscription
      parameters:
      - description: The name of the Microsoft Customer Agreement billing account
          for which you want to create the subscription.
        in: path
        name: billingAccountName
        required: true
        schema:
          type: string
      - description: The name of the customer.
        in: path
        name: customerName
        required: true
        schema:
          type: string
      - description: Version of the API to be used with the client request. Current
          version is 2018-11-01-preview
        in: query
        name: api-version
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModernCspSubscriptionCreationParameters'
        description: The subscription creation parameters.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionCreationResult'
          description: Normal response for a successful query. The response body will
            contain the data that matches the filters specified in the query parameters.
        "202":
          content: {}
          description: Accepted. Subscription creation is in progress.
          headers:
            Retry-After:
              description: The amount of delay to use while the status of the operation
                is checked. The value is expressed in seconds.
              schema:
                type: integer
            Location:
              description: GET this URL to retrieve the status of the asynchronous
                operation.
              schema:
                type: string
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response describing why the operation failed.
      x-ms-examples:
        createSubscription:
          parameters:
            api-version: 2018-11-01-preview
            billingAccountName: 2bc54a6f-8d8a-5be1-5bff-bb4f285f512b:11a72812-d9a4-446e-9a1e-70c8bcadf5c0_2019-05-31
            body:
              displayName: Contoso MCA subscription
              skuId: "0001"
            customerName: e33ba30d-3718-4b15-bfaa-5627a57cda6f
          responses:
            "200":
              body:
                subscriptionLink: /subscriptions/d0d6ee57-6530-4fca-93a6-b755a070be35
            "202":
              headers:
                Location: https://management.azure.com/providers/Microsoft.Subscription/subscriptionOperations/MzcwYzI3MDItNjA1MC00NTZkLTgyMTgtZjM0NDcyMjkwMTY0?api-version=2018-03-01-preview
                Retry-After: 8
      x-ms-long-running-operation: true
      x-codegen-request-body-name: body
      x-content-type: application/json
      x-accepts:
      - application/json
  /providers/Microsoft.Subscription/subscriptionOperations/{operationId}:
    get:
      description: Get the status of the pending Microsoft.Subscription API operations.
      operationId: SubscriptionOperation_Get
      parameters:
      - description: "The operation ID, which can be found from the Location field\
          \ in the generate recommendation response header."
        in: path
        name: operationId
        required: true
        schema:
          type: string
      - description: Version of the API to be used with the client request. Current
          version is 2018-11-01-preview
        in: query
        name: api-version
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionCreationResult'
          description: Successful completion of the asynchronous operation
        "202":
          content: {}
          description: Accepted. Subscription update is in progress.
          headers:
            Retry-After:
              description: The amount of delay to use while the status of the operation
                is checked. The value is expressed in seconds.
              schema:
                type: integer
            Location:
              description: The URL where the status of the asynchronous operation
                can be checked.
              schema:
                type: string
      x-ms-examples:
        getPendingSubscriptionOperations:
          parameters:
            api-version: 2018-11-01-preview
            operationId: e4b8d068-f574-462a-a76f-6fa0afc613c9
          responses:
            "200":
              body:
                subscriptionLink: /subscriptions/4df8d5c2-1b7e-4dd5-bc61-640704bde633
            "202":
              headers:
                Location: /providers/Microsoft.Subscription/subscriptionOperations/e4b8d068-f574-462a-a76f-6fa0afc613c9?api-version=2018-11-01-preview
                Retry-After: 8
      x-accepts:
      - application/json
components:
  parameters:
    apiVersionParameter:
      description: Version of the API to be used with the client request. Current
        version is 2018-11-01-preview
      in: query
      name: api-version
      required: true
      schema:
        type: string
  schemas:
    AdPrincipal:
      description: Active Directory Principal whoâ€™ll get owner access on the new subscription.
      example:
        objectId: objectId
      properties:
        objectId:
          description: Object id of the Principal
          type: string
      required:
      - objectId
      type: object
    ErrorResponse:
      description: Describes the format of Error response.
      example:
        code: code
        message: message
      properties:
        code:
          description: Error code
          type: string
        message:
          description: Error message indicating why the operation failed.
          type: string
      type: object
    ModernCspSubscriptionCreationParameters:
      description: The parameters required to create a new CSP subscription.
      example:
        resellerId: resellerId
        serviceProviderId: serviceProviderId
        displayName: displayName
        skuId: skuId
      properties:
        displayName:
          description: The friendly name of the subscription.
          type: string
        resellerId:
          description: "Reseller ID, basically MPN Id."
          type: string
        serviceProviderId:
          description: "Service provider ID, basically MPN Id."
          type: string
        skuId:
          description: The SKU ID of the Azure plan. Azure plan determines the pricing
            and service-level agreement of the subscription.  Use 001 for Microsoft
            Azure Plan and 002 for Microsoft Azure Plan for DevTest.
          type: string
      required:
      - displayName
      - skuId
      type: object
    ModernSubscriptionCreationParameters:
      description: The parameters required to create a new subscription.
      example:
        managementGroupId: managementGroupId
        owner:
          objectId: objectId
        costCenter: costCenter
        displayName: displayName
        billingProfileId: billingProfileId
        additionalParameters:
          key: "{}"
        skuId: skuId
      properties:
        additionalParameters:
          additionalProperties:
            properties: {}
            type: object
          description: "Additional, untyped parameters to support custom subscription\
            \ creation scenarios."
          type: object
        billingProfileId:
          description: The ARM ID of the billing profile for which you want to create
            the subscription.
          type: string
        costCenter:
          description: "If set, the cost center will show up on the Azure usage and\
            \ charges file."
          type: string
        displayName:
          description: The friendly name of the subscription.
          type: string
        managementGroupId:
          description: The identifier of the management group to which this subscription
            will be associated.
          type: string
        owner:
          $ref: '#/components/schemas/AdPrincipal'
        skuId:
          description: The SKU ID of the Azure plan. Azure plan determines the pricing
            and service-level agreement of the subscription.  Use 001 for Microsoft
            Azure Plan and 002 for Microsoft Azure Plan for DevTest.
          type: string
      required:
      - billingProfileId
      - displayName
      - skuId
      type: object
    Operation:
      description: REST API operation
      properties:
        display:
          $ref: '#/components/schemas/Operation_display'
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          type: string
      type: object
    OperationListResult:
      description: Result of the request to list operations. It contains a list of
        operations and a URL link to get the next set of results.
      properties:
        nextLink:
          description: URL to get the next set of operation list results if there
            are any.
          type: string
        value:
          description: List of operations.
          items:
            $ref: '#/components/schemas/Operation'
          type: array
      type: object
    SubscriptionCreationResult:
      description: The created subscription object.
      example:
        subscriptionLink: subscriptionLink
      properties:
        subscriptionLink:
          description: The link to the new subscription. Use this link to check the
            status of subscription creation operation.
          type: string
      type: object
    SubscriptionOperation:
      description: status of the subscription POST operation.
      properties:
        id:
          description: The operation Id.
          readOnly: true
          type: string
        status:
          description: Status of the pending subscription
          type: string
        statusDetail:
          description: Status Detail of the pending subscription
          type: string
      type: object
    SubscriptionOperationListResult:
      description: A list of pending subscription operations.
      properties:
        value:
          description: A list of pending SubscriptionOperations
          items:
            $ref: '#/components/schemas/SubscriptionOperation'
          type: array
      type: object
    Operation_display:
      description: The object that represents the operation.
      properties:
        operation:
          description: "Operation type: Read, write, delete, etc."
          type: string
        provider:
          description: "Service provider: Microsoft.Subscription"
          type: string
        resource:
          description: "Resource on which the operation is performed: Profile, endpoint,\
            \ etc."
          type: string
      type: object
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2
x-original-swagger-version: "2.0"

